export const DEFAULT_BRANCH_ID = 1;

// Edit this file before a fresh rollout or bootstrap sync if the initial
// branch/city/balance/report definitions must match production-ready values.
export const defaultBootstrapBranchConfig = {
  branch: {
    id: DEFAULT_BRANCH_ID,
    slug: "default",
    name: "Default branch",
    shortName: "Default",
    isActive: true,
  },
  cities: [
    {
      id: 1,
      slug: "zp",
      name: "Запоріжжя",
      shortName: "ЗП",
      documentPrefix: "ЗП",
      isActive: true,
      sortOrder: 10,
    },
    {
      id: 2,
      slug: "dp",
      name: "Дніпро",
      shortName: "ДП",
      documentPrefix: "ДП",
      isActive: true,
      sortOrder: 20,
    },
    {
      id: 3,
      slug: "kr",
      name: "Кривий Ріг",
      shortName: "КР",
      documentPrefix: "КР",
      isActive: true,
      sortOrder: 30,
    },
  ],
  balancePages: [
    {
      slug: "zp",
      citySlug: "zp",
      menuTitle: "ЗП",
      headerTitle: "Запоріжжя",
      fileName: "balanceZP.xlsx",
      isActive: true,
      sortOrder: 10,
    },
    {
      slug: "dp",
      citySlug: "dp",
      menuTitle: "ДП",
      headerTitle: "Дніпро",
      fileName: "balanceDP.xlsx",
      isActive: true,
      sortOrder: 20,
    },
    {
      slug: "kr",
      citySlug: "kr",
      menuTitle: "КР",
      headerTitle: "Кривий Ріг",
      fileName: "balanceKR.xlsx",
      isActive: true,
      sortOrder: 30,
    },
    {
      slug: "ml",
      citySlug: null,
      menuTitle: "ML",
      headerTitle: "ML",
      fileName: "balanceML.xlsx",
      isActive: false,
      sortOrder: 40,
    },
  ],
  reports: [
    {
      reportKey: "report-romashka",
      route: "/report-romashka",
      menuTitle: "Звіт Ромашка",
      fileName: "report_romashka.json",
      allowedRoles: [2],
      isActive: true,
      sortOrder: 20,
    },
    {
      reportKey: "report-debet",
      route: "/report-debet",
      menuTitle: "Дебеторка",
      fileName: "DebetReport.json",
      allowedRoles: [2, 3, 4, 5, 6],
      isActive: true,
      sortOrder: 30,
    },
    {
      reportKey: "report-orders-by-time",
      route: "/orders-by-time",
      menuTitle: "Заявки ТА по часам",
      fileName: "OrderByTimet.json",
      allowedRoles: [2],
      isActive: true,
      sortOrder: 40,
    },
    {
      reportKey: "report-bill-of-lading",
      route: "/bill-of-lading",
      menuTitle: "Зібрані накладні",
      fileName: "BillOfLading.json",
      allowedRoles: [2, 7],
      retentionDays: 365,
      isActive: true,
      sortOrder: 50,
    },
    {
      reportKey: "report-picker-earnings",
      route: "/picker-earnings",
      menuTitle: "Заробіток комплектувальників",
      fileName: "BillOfLading.json",
      allowedRoles: [2],
      retentionDays: 365,
      isActive: true,
      sortOrder: 60,
    },
  ],
};
